### PR TITLE
hometask-1

### PR DESCRIPTION
**Pull request by NastassiaBon**

### CODE REVIEW

**Comment by Kaddyluck** [comment]
1) **File isn't executable**
image
2) Please leave more clear comments. 
What is it "Refactor code", "Refactore code 2"? What did you do in these commits? I don't know until I'll open them. Remember: "Use the body to explain **what** and **why** vs. **how**". 
So better names will be: "Added frozen string literal comment", "Added blank line"
3) Run RoboCop locally before pushing, it will help not to spam one-line commits with Hound fixes

**Review by ramantechart — DISMISSED** [review]
Sync fork with original repo

**Comment by NastassiaBon** [comment]
>     1. **File isn't executable**
>        image
> 
>     2. Please leave more clear comments.
>        What is it "Refactor code", "Refactore code 2"? What did you do in these commits? I don't know until I'll open them. Remember: "Use the body to explain **what** and **why** vs. **how**".
>        So better names will be: "Added frozen string literal comment", "Added blank line"
> 
>     3. Run RoboCop locally before pushing, it will help not to spam one-line commits with Hound fixes

1. I make executable file, but unfortunately i have hound linter issue i cant understand why because my code the same with my colleague. https://github.com/iTechArt-RubyLab/Ruby-Lab/pull/23
2. I rewrite commit history and i m going to use right naming conversion in future. should i add "Refactor commit" in this tasks? 
3. Done

**Comment by ramantechart** [comment]
@NastassiaBon I'm pretty much sure just syncing the fork with the main repository will be more then enough

**Comment by Kaddyluck** [comment]
1) Check Roman's comment
2) Ok. Not necessary, leave it as it is in that PR

**Review by Kaddyluck — APPROVED** [review]

**Pull request merged**
